### ISSUE TITLE
Make a headless version of PostParrot.

### ISSUE THREAD

**Issue by sofusalbertsen** [emmaarfelt/MessageMule#3]
As a user, I would like to run PostParrot in headless mode through the CLI, so that I can run it on my always-on linux server back home.

**Comment by emmaarfelt** [comment]
This has actually already been done by the awesome [rphi](https://github.com/rphi/fb-messenger-autoreply) :-)

**Comment by emmaarfelt** [comment]
This has actually already been done by the awesome [rphi](https://github.com/rphi/fb-messenger-autoreply) :-)
